# Site settings
# in the templates available like {{ site.myvariable }}.
title: Suresh's Photography
email: drsureshchhabra@yahoo.com
brand: Suresh Chhabra
headline: Photographer and Doctor
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 

# Contacts
email: drsureshchhabra@yahoo.com
phone: 9825552129

# Tracking
googleAnalitycsID: UA-83933844-1

